version: "3.7"

services:
  laravel:
    build:
      context: .
      dockerfile: laravel.dockerfile
    container_name: $COMPOSE_PROJECT_NAME-laravel
    environment:
      DB_DATABASE: laravel
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_USERNAME: laravel
      APP_DEBUG: 'true'
      APP_ENV: local
      APP_KEY: ayGbuqVXJakHHvMTZCjKqzhVqMNsHMQs
      LOG_CHANNEL: stderr
    ports:
    - '80:80'
    volumes:
    - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: $COMPOSE_PROJECT_NAME-mysql
    ports:
    - '3306:3306'
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - ./mysql:/var/lib/mysql
